wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716176551
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 61
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
_fields:
  desc: null
  value:
    name: SoftDQN
    tied: false
    uniform_pb: true
    learning_rate: 0.001
    loss_type: Huber
    net: 'hidden_dim: 256

      n_hidden: 2

      '
    replay_buffer: 'alpha: 0.5

      batch_size: 256

      beta: 0.0

      prioritized: true

      replay_buffer_size: 100000

      '
    munchausen: 'alpha: 0.0

      l0: 0

      '
    learning_starts: 16
    update_frequency: 1
    target_network_frequency: 1
    tau: 0.25
    is_double: false
_locked:
  desc: null
  value: true
_type_safe:
  desc: null
  value: true
_convert_dict:
  desc: null
  value: true
