wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716176003
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
_fields:
  desc: null
  value:
    seed: 3
    device: cuda:0
    validation_interval: 100
    validation_samples: 200000
    wandb_project: GFlowNets as Soft-RL
    n_envs: 256
    n_trajectories: 1000000
_locked:
  desc: null
  value: true
_type_safe:
  desc: null
  value: true
_convert_dict:
  desc: null
  value: true
